### ISSUE TITLE
Name conflicts with other project

### ISSUE THREAD

**Issue by waddlesplash** [Marak/pdf.js#19]
The name "pdf.js" conflicts with Mozilla's PDF reader [pdf.js](https://github.com/mozilla/pdf.js), another GitHub project (and more popular than Marak/pdf.js).

I would suggest you change the name so that others can find you easier.
Perhaps "makepdf.js"?

**Comment by Marak** [comment]
I made this out of necessity, way before that other one existed.

If the Mozilla people ask, I'll give them the project name. If not, I don't care.

**Comment by waddlesplash** [comment]
I mean that it will hurt your project because when people search for "pdf.js", the Mozilla one comes up first.

**Comment by Marak** [comment]
Thank you for your concerns.
